Генерация данных
htmlacademy-javascript/2122353-kekstagram-26 pull request #4
Opened 2022-06-20 11:24 UTC by LevshaBalIrina

2022-06-20 20:16 UTC, coderoman requested changes

2022-06-20 20:16 UTC, coderoman commented on js/main.js
> +  const user = USERS.find((element) => element.id === userId);
Предлагаю здесь немного переделать, чтобы комментарии получались от разных пользователей. Сейчас выходит, что каждый пользователь выбрал по одной фотке и яростно строчит под ней несколько комментариев.

Поскольку Users это просто массив, то случайного пользователи можно получить просто по индексу, без использования find.

Строчки 49 и 50 нам больше не понадобятся, а внутри цикла мы можем сделать вот так:
```
const randomIndex = getRandomPositiveInteger(0, USERS.length - 1);
const user = USERS[randomIndex];
```

2022-06-20 20:16 UTC, coderoman commented on js/main.js
> +    if(items.find((element) => element.id === id)) {
Find итерирует по элементам в поисках удовлетворяющего условию, соотвествено,  на каждую итерацию while мы имеем итерацию по массиву `items`. Учитывая что айдишник выбирается случайным образом, а `items` постоянно увеличивается  итераций получается много. 

Предлагаю просто сделать id порядковыми 1 до 25 и избавится здесь от find. 

В целом, каждый раз, когда видим цикл внутри цикла, нужно быть начеку, ведь пройдясь 100 раз по каждому из 100 элементов, мы получим уже 10000 итераций, если каждую такую итерацию выполняется какая-то работа, то интерфейс перестанет быть отзывчивым и устройство пользователя начнет тормозить.

2022-06-20 20:16 UTC, coderoman commented on js/main.js
> +      id:  String(parrentId) + i,
Вместо использования `parentId `, можно сделать id  случайным, и к нему уже добавить индекс, чтобы избежать повторени айдишника.

2022-06-21 20:27 UTC, LevshaBalIrina commented on js/main.js
> +  const user = USERS.find((element) => element.id === userId);
Исправила

2022-06-21 20:27 UTC, LevshaBalIrina commented on js/main.js
> +    if(items.find((element) => element.id === id)) {
Исправила

2022-06-21 20:27 UTC, LevshaBalIrina commented on js/main.js
> +      id:  String(parrentId) + i,
Исправила

2022-06-22 06:38 UTC, coderoman commented on js/main.js
> +  const generatedIds = Array.from(Array(ITEMS_COUNT).keys()).map((index) => index + 1);
Здесь можно было зделать чуть попроще, без создания промежуточных массивов:
`Array.from({length: ITEMS_COUNT}, (_, index) => index + 1);`

2022-06-22 06:39 UTC, coderoman approved these changes

2022-06-22 06:39 UTC, merged