8.2 & 9.9
htmlacademy-javascript/2122353-kekstagram-26 pull request #8
Opened 2022-07-21 22:06 UTC by LevshaBalIrina

2022-07-22 20:03 UTC, coderoman requested changes

2022-07-22 20:03 UTC, coderoman commented on js/effects.js
> +  return Number(currentValue.slice(0, -1));
Можно было кстати применить `parseInt(currentValue)`, тот редкий случай, для которого оно было придумано.

2022-07-22 20:03 UTC, coderoman commented on js/effects.js
> +const changeScaleValue = (lower = true) => {
В целом, лучше такого избегать, две функции читаются проще и веселее, одна для добавления, другая для уменьшения. Но это просто общее наблюдение о флагах переключающих поведение.

2022-07-22 20:03 UTC, coderoman commented on js/main.js
> +      const currentCommentsCountObject = evt.target.parentElement.querySelector('.current-comments-count');
Выше уже есть  `parentElement`, поэтом можно просто `parentElement.querySelector`

2022-07-22 20:03 UTC, coderoman commented on js/main.js
> +    const pictureId = parentElement.id ? Number(parentElement.id): null;
Можно было даже не проверять на наличие айдишника, а просто сделать преобразование, если там не число, то вернется `NaN`, а он `falsy` значение.

`const pictureId = Number(parentElement.id);`

if (pictureId) {
  ...
}

2022-07-22 20:03 UTC, coderoman commented on js/main.js
> +      sliceComments.forEach((element) => {
Здесь лучше избежать работы с домом в цикле, создать фрагмент, накидать в него комментов, а потом уже добавить это все кучкой на страницу.
```
const fragment = document.createDocumentFragment();
  sliceComments.forEach((element) => {
  const commentLi = drawComment(parentElement, element);
  fragment.appendChild(commentLi);
  currentComments += 1
});
parentElement.querySelector('.social__comments').appendChild(fragment);
```

2022-07-22 20:03 UTC, coderoman commented on js/main.js
> +      const sliceComments = comments.slice(currentComments, currentComments + COMMENT_VIEW_DEFAULT_COUNT);
Здесь можно добавить еще обновление числа показанных комментов на странице, чтобы это все корректно работало когда там больше одной дополнительной страницы комментов.

```
const offset = currentComments + COMMENT_VIEW_DEFAULT_COUNT;
parentElement.querySelector('.current-comments-count').textContent = offset;
```

2022-07-23 17:35 UTC, LevshaBalIrina commented on js/main.js
> +      const sliceComments = comments.slice(currentComments, currentComments + COMMENT_VIEW_DEFAULT_COUNT);
Я выше в цикле добавляю единицу к currentComments;
`parentElement.querySelector('.current-comments-count').textContent = currentComments;`

2022-07-23 17:36 UTC, LevshaBalIrina commented on js/effects.js
> +  return Number(currentValue.slice(0, -1));
Поменяла

2022-07-23 17:36 UTC, LevshaBalIrina commented on js/effects.js
> +const changeScaleValue = (lower = true) => {
Сделала две функции вместо одной

2022-07-23 17:36 UTC, LevshaBalIrina commented on js/main.js
> +      const currentCommentsCountObject = evt.target.parentElement.querySelector('.current-comments-count');
исправила

2022-07-23 17:36 UTC, LevshaBalIrina commented on js/main.js
> +    const pictureId = parentElement.id ? Number(parentElement.id): null;
исправила

2022-07-23 17:36 UTC, LevshaBalIrina commented on js/main.js
> +      sliceComments.forEach((element) => {
исправила

2022-07-23 19:32 UTC, coderoman approved these changes

2022-07-23 19:33 UTC, merged